Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> # creating a dictionary
>>> dict = {}
>>> # adding some entries to the dictionary
>>> dict['floccinaucinihilipilification'] = "the action or habit of estimating something as worthless."
>>> dict['bumfuzzle'] = "confuse; perplex; fluster"
>>> dict['taradiddle'] = "pretentious nonsense"
>>> # checking some known entries in the dictionary
>>> dict['floccinaucinihilipilification']
'the action or habit of estimating something as worthless.'
>>> dict['bumfuzzle']
'confuse; perplex; fluster'
>>> dict['taradiddle']
'pretentious nonsense'
>>> # checking an unknown entry in the dictionry 
>>> dict['nonsense']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'nonsense'
>>> exit()

